### ISSUE TITLE
Failed to generate report

### ISSUE THREAD

**Issue by bihihinok** [FortyNorthSecurity/EyeWitness#338]
## Output of uname -a
```
Linux debian-s-2vcpu-4gb-blr1-01 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
```
## Error Output
```
Attempting to screenshot http://ot100u.x.com
[*] Sleeping for 2.16 seconds..
Attempting to screenshot http://pay.test.x.com
[*] Sleeping for 2.37 seconds..
Attempting to screenshot http://pbr-www.test.pay.x.com
[*] Sleeping for 2.76 seconds..
Traceback (most recent call last):
  File "EyeWitness/EyeWitness.py", line 646, in <module>
    multi_mode(cli_parsed)
  File "EyeWitness/EyeWitness.py", line 574, in multi_mode
    sort_data_and_write(cli_parsed, results)
  File "/root/tools/EyeWitness/modules/reporting.py", line 225, in sort_data_and_write
    html += obj.create_table_html()
  File "/root/tools/EyeWitness/modules/objects.py", line 248, in create_table_html
    for key, value in self.headers.items():
AttributeError: 'str' object has no attribute 'items'
```

## Expected behavior (vs. what you encountered)

It should generate the html report, which it isn't

**Comment by ChrisTruncer** [comment]
Does it always get stuck on a single site? One thing you could do is run Reconfigure.py and pass it the path to your ew.db file (within your EyeWitness results folder). It will then generate a report based on the information collected prior to the crash.

**Comment by ChrisTruncer** [comment]
Can you give any additional info?

**Comment by ChrisTruncer** [comment]
closing due to no response
