### ISSUE TITLE
error while runing EyeWitness.py

### ISSUE THREAD

**Issue by sr666452** [FortyNorthSecurity/EyeWitness#341]
Traceback (most recent call last):
  File "./EyeWitness.py", line 13, in <module>
    from modules import db_manager
  File "/root/EyeWitness/modules/db_manager.py", line 4, in <module>
    from objects import HTTPTableObject
  File "/root/EyeWitness/modules/objects.py", line 5, in <module>
    from helpers import strip_nonalphanum
  File "/root/EyeWitness/modules/helpers.py", line 15, in <module>
    from login_module import checkCreds
  File "/root/EyeWitness/modules/login_module.py", line 8, in <module>
    from bs4 import BeautifulSoup as beatsop
  File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'
any help

**Comment by ChrisTruncer** [comment]
Hi there,

Please provide all the information requested in the Github issue template, otherwise there isn’t enough info to help troubleshoot.

Thanks

**Comment by sr666452** [comment]
Hello sir,
I am using kali linux 2018.2 latest version arch x86_64
when i run ./EyeWitness.py --help they show me error 
Traceback (most recent call last):
  File "EyeWitness.py", line 13, in <module>
    from modules import db_manager
  File "/root/EyeWitness/modules/db_manager.py", line 4, in <module>
    from objects import HTTPTableObject
  File "/root/EyeWitness/modules/objects.py", line 5, in <module>
    from helpers import strip_nonalphanum
  File "/root/EyeWitness/modules/helpers.py", line 15, in <module>
    from login_module import checkCreds
  File "/root/EyeWitness/modules/login_module.py", line 8, in <module>
    from bs4 import BeautifulSoup as beatsop
  File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'
i was expected to show help option..
i was copy and paste error to google and try all thing but nothing work 
now what i do

**Comment by ChrisTruncer** [comment]
Please clone from Github and try running the install script

**Comment by sr666452** [comment]
not working  same error
