### ISSUE TITLE
Error while generating report

### ISSUE THREAD

**Issue by xdavidhu** [FortyNorthSecurity/EyeWitness#342]
### Output of `uname -a`:
`Linux hostname 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

### Crash log, including `Recategorize.py`:
`https://pastebin.com/pCexhMdN`

## Expected behavior (vs. what you encountered)
It should generate the HTML report, but It fails. It happens on multiple sites.

**Comment by ChrisTruncer** [comment]
Are you able to debug it and see where exactly it is failing, the data it is reading, etc.? Or are you able to share the sites you were scanning so I can try to recreate it?

**Comment by xdavidhu** [comment]
By adding a print to `line 247` of `modules/objects.py`:
```
            except UnicodeEncodeError:
                html += u"\n<br><b> Page Title:</b>{0}\n".format(
                    self.sanitize(self.page_title))
            print "----------self.headers----------"
            print self.headers;
            print "--------------------------------"
            for key, value in self.headers.items():
                try:
                    html += '<br><b> {0}:</b> {1}\n'.format(
```
I'm getting this as a header "object" in the for loop:
```
110/142
120/142
130/142
140/142
Writing report
----------self.headers----------
{'content-length': '166', 'server': 'NetDNA-cache/2.2', 'connection': 'close', 'date': 'Mon, 20 Aug 2018 16:26:54 GMT', 'Response Code': '502', 'content-type': 'text/html'}
--------------------------------
----------self.headers----------
No Data Collected
--------------------------------
Traceback (most recent call last):
  File "Recategorize.py", line 50, in <module>
    sort_data_and_write(cli_parsed, results)
  File "/root/tools/EyeWitness/modules/reporting.py", line 225, in sort_data_and_write
    html += obj.create_table_html()
  File "/root/tools/EyeWitness/modules/objects.py", line 250, in create_table_html
    for key, value in self.headers.items():
AttributeError: 'str' object has no attribute 'items'
```
I would assume it's because of `line 137` of `modules/objects.py`:
```
    @property
    def headers(self):
        if hasattr(self, '_headers'):
            return self._headers
        else:
            return "No Data Collected"
```

**Comment by ChrisTruncer** [comment]
OK thanks. I'll try to modify this shortly. I might be able to make a python dict stating that states there aren't any headers.
