### ISSUE TITLE
XML Parsing error

### ISSUE THREAD

**Issue by Thestorm77** [FortyNorthSecurity/EyeWitness#363]
## OS Used - Ubuntu 16.04 x64 

When trying to use the -x switch for nmap xml file i get the following error 

The command used is: *sudo ./EyeWitness.py -x scan.xml --web*

 FortyNorth Security - https://www.fortynorthsecurity.com           #
################################################################################

Traceback (most recent call last):
  File "./EyeWitness.py", line 646, in <module>
    multi_mode(cli_parsed)
  File "./EyeWitness.py", line 455, in multi_mode
    url_list, rdp_list, vnc_list = target_creator(cli_parsed)
  File "/pentest/intelligence-gathering/eyewitness/modules/helpers.py", line 514, in target_creator
    parser.parse(command_line_object.x)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 125, in parse
    self.close()
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 225, in close
    self.feed("", isFinal = 1)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 217, in feed
    self._err_handler.fatalError(exc)
  File "/usr/lib/python2.7/xml/sax/handler.py", line 38, in fatalError
    raise exception
xml.sax._exceptions.SAXParseException: scan.xml:15664:0: no element found

The xml file has a number of servers with open ports 80 and 443. 

Not sure why this is occurring

**Comment by ChrisTruncer** [comment]
Did you pause or resume your scan at any point? The most likely reason for an xml parsing error is malformed XML since it would have to be exactly what the parser expects.

Can you check that first, and if you think it’s still ok, upload the xml?

**Comment by Thestorm77** [comment]
I feel so dumb right about now. It looks like the scan never completed before Eyewitness kicked in. So once it completed I no longer receive the same error. I do however get this 

################################################################################
#                                  EyeWitness                                  #
################################################################################
#           FortyNorth Security - https://www.fortynorthsecurity.com           #
################################################################################

Traceback (most recent call last):
  File "./EyeWitness.py", line 646, in <module>
    multi_mode(cli_parsed)
  File "./EyeWitness.py", line 455, in multi_mode
    url_list, rdp_list, vnc_list = target_creator(cli_parsed)
  File "/pentest/intelligence-gathering/eyewitness/modules/helpers.py", line 514, in target
_creator
    parser.parse(command_line_object.x)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 217, in feed
    self._err_handler.fatalError(exc)
  File "/usr/lib/python2.7/xml/sax/handler.py", line 38, in fatalError
    raise exception
xml.sax._exceptions.SAXParseException: scan.xml:15663:1: not well-formed (invalid token)

**Comment by ChrisTruncer** [comment]
No reason to feel dumb!

With that said, I still think my previous statement is the likely cause, that the XML file is malformed somewhere and causing this error.

**Comment by Thestorm77** [comment]
Reran the scan and the file is now being processed. 

Thank You, 
Armend M.
