### ISSUE TITLE
Error When running EyeWitness

### ISSUE THREAD

**Issue by lolos12** [FortyNorthSecurity/EyeWitness#393]
## OS Used - ALL Information (architecture, linux flavor, etc.)
I'm Using Kali Linux 

Linux kali 4.14.0-kali3-amd64 #1 SMP Debian 4.14.12-2kali1 (2018-01-08) x86_64 GNU/Linux

## Pastebin link to error you are encountering

https://pastebin.com/p7Y5Mb7B

## Expected behavior (vs. what you encountered)
I expect it to run normally but I get this error : 
`TypeError: attr() got an unexpected keyword argument 'converter'`
or
`AttributeError: 'module' object has no attribute 's'`
## Any additional information
Hi :) .

EyeWitness used to work flawlessly but  suddely I have the following issue
(i had not used it in while)
I'm using kali linux
I have tried a fresh install but when I try to run it I get:

`TypeError: attr() got an unexpected keyword argument 'converter'`

I search the net and I think that it has  to do with the Attr() that something has been renamed from  convert to converter

> https://github.com/Julian/jsonschema/issues/449

> Your attrs version is too old. It used to be convert which is now deprecated and called converter instead

Maybe i'm doing something wrong with the Attr installation or a wrongly installed Python exists maybe

I tried doing `pip install attr` which change the error to 
`AttributeError: 'module' object has no attribute 's'`
 
but then again `pip install attrs` and again the converter error

P.S.:I face the same issue with the EyeWitness installation of [domained](https://github.com/reconned/domained) which again installs EyeWitness independently

---------------------------------------------------------------------------------------------------------------
outputs:
**without attrs**
root@kali:~/Downloads/EyeWitness# ./EyeWitness.py  --web -f /root/aquatone/riotgames.com/urls.txt 
Traceback (most recent call last):
  File "./EyeWitness.py", line 16, in <module>
    from modules import rdp_module
  File "/root/Downloads/EyeWitness/modules/rdp_module.py", line 8, in <module>
    from rdpy.protocol.rdp import rdp
  File "build/bdist.linux-x86_64/egg/rdpy/protocol/rdp/rdp.py", line 30, in <module>
  File "build/bdist.linux-x86_64/egg/rdpy/protocol/rdp/x224.py", line 313, in <module>
  File "/usr/lib/python2.7/dist-packages/twisted/internet/ssl.py", line 65, in <module>
    from twisted.internet import tcp, interfaces
  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 31, in <module>
    from twisted.internet._newtls import (
  File "/usr/lib/python2.7/dist-packages/twisted/internet/_newtls.py", line 21, in <module>
    from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol
  File "/usr/lib/python2.7/dist-packages/twisted/protocols/tls.py", line 61, in <module>
    from twisted.internet._producer_helpers import _PullToPush
  File "/usr/lib/python2.7/dist-packages/twisted/internet/_producer_helpers.py", line 13, in <module>
    from twisted.internet.task import cooperate
  File "/usr/lib/python2.7/dist-packages/twisted/internet/task.py", line 25, in <module>
    from twisted.internet import base, defer
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 27, in <module>
    from twisted.internet._resolver import (
  File "/usr/lib/python2.7/dist-packages/twisted/internet/_resolver.py", line 25, in <module>
    from twisted.internet.address import IPv4Address, IPv6Address
  File "/usr/lib/python2.7/dist-packages/twisted/internet/address.py", line 103, in <module>
    class UNIXAddress(object):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/address.py", line 111, in UNIXAddress
    name = attr.ib(converter=attr.converters.optional(_asFilesystemBytes))
TypeError: attr() got an unexpected keyword argument 'converter'

**with attrs:**
root@kali:~/Downloads/EyeWitness# ./EyeWitness.py  --web  -f /root/aquatone/riotgames.com/urls.txt 
Traceback (most recent call last):
  File "./EyeWitness.py", line 16, in <module>
    from modules import rdp_module
  File "/root/Downloads/EyeWitness/modules/rdp_module.py", line 8, in <module>
    from rdpy.protocol.rdp import rdp
  File "build/bdist.linux-x86_64/egg/rdpy/protocol/rdp/rdp.py", line 24, in <module>
  File "build/bdist.linux-x86_64/egg/rdpy/core/layer.py", line 107, in <module>
  File "/usr/lib/python2.7/dist-packages/twisted/internet/protocol.py", line 18, in <module>
    from twisted.internet import interfaces, error, defer
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1366, in <module>
    @attr.s
AttributeError: 'module' object has no attribute 's'

**Comment by ChrisTruncer** [comment]
Did you install this by cloning down via git, running the setup script, and then running EyeWitness, or possibly through apt? I can't seem to get these errors.

**Comment by lolos12** [comment]
Yes,I cloned the git then cd in the directory, cd in setup and executed the setup script which runs without errors.
As I said domained installs EyeWitness independently  the same way and I get the same issue.
Maybe it has something to do with my Python installation but I can't figure what causes it.

Do you want anymore logs?

**Comment by ChrisTruncer** [comment]
Honestly, I'm not certain what else to ask for. I just tested a clean install of Kali with EyeWitness (cloned from the repo), and the setup ran successfully. When I tried running EyeWitness, everything worked (took screenshots, generated the report, etc.). It leads me to think it is something with your local install. Could you try on a clean Kali install too?

**Comment by porterhau5** [comment]
Happened to me too. Resolved it by updating my attrs: ```pip install attrs --upgrade```.
