### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by digininja** [FortyNorthSecurity/EyeWitness#396]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Debian 9.9

## Pastebin link to error you are encountering

Just pulled the latest version from GitHub and got this:

```
$ ~/tools/web/EyeWitness/EyeWitness.py -x basic.xml -d eyewitness_external --web
Traceback (most recent call last):
  File "/home/robin/tools/web/EyeWitness/EyeWitness.py", line 16, in <module>
    from modules import rdp_module
  File "/opt/tools/web/EyeWitness/modules/rdp_module.py", line 8, in <module>
    from rdpy.protocol.rdp import rdp
  File "build/bdist.linux-x86_64/egg/rdpy/protocol/rdp/rdp.py", line 30, in <module>
  File "build/bdist.linux-x86_64/egg/rdpy/protocol/rdp/x224.py", line 313, in <module>
  File "/usr/local/lib/python2.7/dist-packages/Twisted-15.3.0-py2.7-linux-x86_64.egg/twisted/internet/ssl.py", line 59, in <module>
    from OpenSSL import SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
```

## Expected behavior (vs. what you encountered)
It work!

## Any additional information

Need to add this to the setup script

```
pip install -U pyopenssl
```

**Comment by ChrisTruncer** [comment]
I'll need to do some more testing on my end. I did a quick test on 9.9 and EyeWitness worked, but I didn't pass in the XML input. Did this work if you just tested it with --single or --file? Or was it completely broken until you installed that dependency?

**Comment by digininja** [comment]
It used to work but hadn't used it on that box for a while. I re-ran the setup script then tried the command above and it failed. Googled the last error, found the suggestion of installing/upgrading pyopenssl, did that, and then it worked.

**Comment by DannyCork** [comment]
I had a similar problem in https://github.com/FortyNorthSecurity/EyeWitness/issues/404 
My problem was that I had pyOpenSSL-13 installed.

once I removed that and installed pyOpenSSL-19 , EyeWitness worked.

**Comment by ChrisTruncer** [comment]
This is merged in now, so I will close this out.

Thanks!
