### ISSUE TITLE
Program install error! 

### ISSUE THREAD

**Issue by kali3426** [FortyNorthSecurity/EyeWitness#415]
Traceback (most recent call last):
  File "EyeWitness.py", line 611, in <module>
    multi_mode(cli_parsed)
  File "EyeWitness.py", line 431, in multi_mode
    display = Display(visible=0, size=(1920, 1080))
  File "/usr/local/lib/python2.7/dist-packages/pyvirtualdisplay/display.py", line 34, in __init__
    self._obj = self.display_class(
  File "/usr/local/lib/python2.7/dist-packages/pyvirtualdisplay/display.py", line 53, in display_class
    cls.check_installed()
  File "/usr/local/lib/python2.7/dist-packages/pyvirtualdisplay/xvfb.py", line 40, in check_installed
    ubuntu_package=PACKAGE).check_installed()
  File "/usr/local/lib/python2.7/dist-packages/easyprocess/__init__.py", line 182, in check_installed
    raise EasyProcessCheckInstalledError(self)
easyprocess.EasyProcessCheckInstalledError: cmd=['Xvfb', '-help']
OSError=[Errno 2] No such file or directory
Program install error!

**Comment by ChrisTruncer** [comment]
Did you run the setup script?
