### ISSUE TITLE
no netaddr in Python3

### ISSUE THREAD

**Issue by digininja** [FortyNorthSecurity/EyeWitness#417]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Up to date Kali

## Pastebin link to error you are encountering

Python 3 branch.

```
$ git branch
* Python3
  master
```

Get this running with a known good XML file

```
$ python3 ./EyeWitness.py --web -x ~/client/test/web_test.xml
Traceback (most recent call last):
  File "./EyeWitness.py", line 13, in <module>
    from modules import db_manager
  File "/home/robin/tools/EyeWitness/modules/db_manager.py", line 4, in <module>
    from modules.objects import HTTPTableObject
  File "/home/robin/tools/EyeWitness/modules/objects.py", line 5, in <module>
    from modules.helpers import strip_nonalphanum
  File "/home/robin/tools/EyeWitness/modules/helpers.py", line 13, in <module>
    from netaddr import IPAddress
ModuleNotFoundError: No module named 'netaddr'
```

## Expected behaviour (vs. what you encountered)

Crash bad, work it should.

## Any additional information

Master works fine

**Comment by digininja** [comment]
You fixed it

**Comment by maheshbasnet089** [comment]
how to fix this issue ?
