### ISSUE TITLE
webdriver exception

### ISSUE THREAD

**Issue by digininja** [FortyNorthSecurity/EyeWitness#418]
```
Process Process-2:
Traceback (most recent call last):
  File "/home/robin/tools/EyeWitness/modules/selenium_module.py", line 93, in capture_host
    driver.get(http_object.remote_system)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=http%3A//10.0.63.29/&c=UTF-8&f=regular&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%2010.0.63.29.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "./EyeWitness.py", line 290, in worker_thread
    cli_parsed, http_object, driver)
  File "/home/robin/tools/EyeWitness/modules/selenium_module.py", line 103, in capture_host
    except httplib.BadStatusLine:
NameError: name 'httplib' is not defined
Process Process-3:
Traceback (most recent call last):
  File "/home/robin/tools/EyeWitness/modules/selenium_module.py", line 93, in capture_host
    driver.get(http_object.remote_system)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=https%3A//10.0.63.29/&c=UTF-8&f=regular&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%2010.0.63.29.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "./EyeWitness.py", line 290, in worker_thread
    cli_parsed, http_object, driver)
  File "/home/robin/tools/EyeWitness/modules/selenium_module.py", line 103, in capture_host
    except httplib.BadStatusLine:
NameError: name 'httplib' is not defined
Traceback (most recent call last):
  File "./EyeWitness.py", line 469, in <module>
    duplicate_check(cli_parsed)
  File "/home/robin/tools/EyeWitness/modules/helpers.py", line 262, in duplicate_check
    for num in xrange(1, total_files):
NameError: name 'xrange' is not defined
```

**Comment by digininja** [comment]
Came straight after

```
Starting Web Requests (4 Hosts)
Attempting to screenshot http://10.0.63.28
Attempting to screenshot https://10.0.63.28
Attempting to screenshot http://10.0.63.29
Attempting to screenshot https://10.0.63.29
Process Process-2:
```

**Comment by digininja** [comment]
Nearly:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "./EyeWitness.py", line 290, in worker_thread
    cli_parsed, http_object, driver)
  File "/home/robin/tools/EyeWitness/modules/selenium_module.py", line 103, in capture_host
    except httplib.BadStatusLine:
NameError: name 'httplib' is not defined
Finished in 8.828114032745361 seconds
```

**Comment by digininja** [comment]
Fixed.
