### ISSUE TITLE
Crash when attempting to scan Axis cameras

### ISSUE THREAD

**Issue by Sw3dishPh1sh** [FortyNorthSecurity/EyeWitness#451]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Kali Linux

## Pastebin link to error you are encountering
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/eyewitness/EyeWitness.py", line 284, in worker_thread
    cli_parsed, http_object, driver)
  File "/usr/share/eyewitness/modules/selenium_module.py", line 183, in capture_host
    driver.save_screenshot(http_object.screenshot_path)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 1097, in save_screenshot
    return self.get_screenshot_as_file(filename)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 1072, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 1108, in get_screenshot_as_png
    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
AttributeError: 'NoneType' object has no attribute 'encode'

## Expected behavior (vs. what you encountered)
Expected behavior would be for the scan to continue, when encountering an Axis camera the scan stops and displays a message like it ended normally.

**Comment by ChrisTruncer** [comment]
Can you provide a public IP of a system (feel free to e-mail or DM me) and I can review this

**Comment by ChrisTruncer** [comment]
Closing due to inactivity

**Comment by barrett092** [comment]
Same here with Axis cameras as well.
