### ISSUE TITLE
Getting this issue in Eyewitness. In Kali as well as ubantu

### ISSUE THREAD

**Issue by Nikhil15292** [FortyNorthSecurity/EyeWitness#464]
Traceback (most recent call last):
  File "./EyeWitness.py", line 13, in <module>
    from modules import db_manager
  File "/mnt/c/Users/nemad/Desktop/Applications/EyeWitness/modules/db_manager.py", line 4, in <module>
    from modules.objects import HTTPTableObject
  File "/mnt/c/Users/nemad/Desktop/Applications/EyeWitness/modules/objects.py", line 5, in <module>
    from modules.helpers import strip_nonalphanum
  File "/mnt/c/Users/nemad/Desktop/Applications/EyeWitness/modules/helpers.py", line 13, in <module>
    from netaddr import IPAddress
ModuleNotFoundError: No module named 'netaddr

**Comment by digininja** [comment]
The netaddr package is installed by the setup script, did you run that?

**Comment by Nikhil15292** [comment]
Issue has been resolved. Yes it was in set up  I run it and it resolved the
issue.  But while I run it shows failed to decode response from marionette.
What does that mean?

**Comment by digininja** [comment]
Raise a new issue and give some more details.

Command you are running, the error message, the environment you are running
in etc.

**Comment by Nikhil15292** [comment]
Okey thanks ..

**Comment by digininja** [comment]
And remember to close this issue
