### ISSUE TITLE
Sometime This Error Happen

### ISSUE THREAD

**Issue by badr-azeez** [FortyNorthSecurity/EyeWitness#483]
```
Traceback (most recent call last):
  File "EyeWitness.py", line 424, in <module>
    multi_mode(cli_parsed)
  File "EyeWitness.py", line 366, in multi_mode
    sort_data_and_write(cli_parsed, results)
  File "/root/EyeWitness/Python/modules/reporting.py", line 216, in sort_data_and_write
    errors = sorted([x for x in data if x.error_state is not None],
TypeError: '<' not supported between instances of 'str' and 'NoneType'
```

**Comment by ChrisTruncer** [comment]
Can you provide additional information (like what was requested when you create the issue)? Can you provide the URL(s) that you were scanning?

**Comment by badr-azeez** [comment]
sorry can't  i use 
`python3 EyeWitness.py --resume ~/test/ew.db 
`

**Comment by ChrisTruncer** [comment]
I don't have that database file. If you could please provide the URLs that you were scanning then we can look to see if we can re-create a bug.

**Comment by badr-azeez** [comment]
```
[*] Hit timeout limit when connecting to https://growth3.box.lab.smartsheet.com:443/, retrying
Traceback (most recent call last):
  File "EyeWitness.py", line 424, in <module>
    multi_mode(cli_parsed)
  File "EyeWitness.py", line 366, in multi_mode
    sort_data_and_write(cli_parsed, results)
  File "/media/badr/BADR_500/MY_FILE/hacker/scripts/web/subdomain/EyeWitness/Python/modules/reporting.py", line 216, in sort_data_and_write
    errors = sorted([x for x in data if x.error_state is not None],
TypeError: '<' not supported between instances of 'NoneType' and 'str'
```
