### ISSUE TITLE
not working properly showing error

### ISSUE THREAD

**Issue by MrtkHacK3R** [FortyNorthSecurity/EyeWitness#504]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/easyprocess/__init__.py", line 169, in start
    cmd, stdout=stdout, stderr=stderr, cwd=self.cwd, env=self.env,
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'Xvfb': 'Xvfb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./EyeWitness.py", line 424, in <module>
    multi_mode(cli_parsed)
  File "./EyeWitness.py", line 335, in multi_mode
    display = Display(visible=0, size=(1920, 1080))
  File "/usr/local/lib/python3.7/dist-packages/pyvirtualdisplay/display.py", line 58, in __init__
    **kwargs
  File "/usr/local/lib/python3.7/dist-packages/pyvirtualdisplay/xvfb.py", line 54, in __init__
    extra_args=extra_args,
  File "/usr/local/lib/python3.7/dist-packages/pyvirtualdisplay/abstractdisplay.py", line 87, in __init__
    helptext = get_helptext(program)
  File "/usr/local/lib/python3.7/dist-packages/pyvirtualdisplay/util.py", line 10, in get_helptext
    p.call()
  File "/usr/local/lib/python3.7/dist-packages/easyprocess/__init__.py", line 141, in call
    self.start().wait(timeout=timeout)
  File "/usr/local/lib/python3.7/dist-packages/easyprocess/__init__.py", line 174, in start
    raise EasyProcessError(self, "start error")
easyprocess.EasyProcessError: start error <EasyProcess cmd_param=['Xvfb', '-help'] cmd=['Xvfb', '-help'] oserror=[Errno 2] No such file or directory: 'Xvfb': 'Xvfb' return_code=None stdout="None" stderr="None" timeout_happened=False>

**Comment by TeeReyx** [comment]
Hello, you can try installing xvfb. I ran into the issue earlier as well. Here is a link to the [fix](https://www.blackhillsinfosec.com/fixing-eyewitness-install-errors-on-kali-linux/)
