### ISSUE TITLE
Permission denied: 'screens'

### ISSUE THREAD

**Issue by kedibeauty2425** [FortyNorthSecurity/EyeWitness#535]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Linux parrot 5.10.0-6parrot1-amd64 #1 SMP Debian 5.10.28-6parrot1 (2021-04-12) x86_64 GNU/Linux
## Any additional information
eyewitness --web -f filepath -d outputpath

when I run the above command

Traceback (most recent call last):
  File "/usr/share/eyewitness/EyeWitness.py", line 379, in <module>
    cli_parsed = create_cli_parser()
  File "/usr/share/eyewitness/EyeWitness.py", line 167, in create_cli_parser
    shutil.rmtree(args.d)
  File "/usr/lib/python3.9/shutil.py", line 718, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.9/shutil.py", line 659, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/usr/lib/python3.9/shutil.py", line 657, in _rmtree_safe_fd
    os.rmdir(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'screens'

above error occur 

how to resolve the error..?

**Comment by digininja** [comment]
Looks like you are running it from a directory your user doesn't have write
permission for, try running it from a different directory.

**Comment by ChrisTruncer** [comment]
Thanks @digininja, That's exactly my thoughts. Closing this for now, but feel free to post new info if something else comes along with this issue
